"""ux_workspaces column in model user

Revision ID: 2088c1841256
Revises: b3524c002189
Create Date: 2021-04-20 09:14:12.946716

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2088c1841256'
down_revision = 'b3524c002189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ux_workspaces', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ux_workspaces')
    # ### end Alembic commands ###
