"""add tablemeta table

Revision ID: 20d7ecaca17c
Revises: 785f433e29da
Create Date: 2021-05-06 16:23:20.761402

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '20d7ecaca17c'
down_revision = '785f433e29da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tablemetas_table_data', table_name='tablemetas')
    op.drop_column('tablemetas', 'table_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablemetas', sa.Column('table_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_tablemetas_table_data', 'tablemetas', ['table_data'], unique=False)
    # ### end Alembic commands ###
