"""add post table + migration

Revision ID: 20fb41f19d89
Revises: 472f42a14cea
Create Date: 2021-03-25 19:57:16.266557

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '20fb41f19d89'
down_revision = '472f42a14cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
