"""adding columns to user table : workspaces and datasets..

Revision ID: 23131606ded8
Revises: c9beacec9912
Create Date: 2021-04-16 18:39:08.912137

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '23131606ded8'
down_revision = 'c9beacec9912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
