"""add tablemeta table

Revision ID: 273a44740963
Revises: 6d253843cadf
Create Date: 2021-05-06 14:56:38.257480

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '273a44740963'
down_revision = '6d253843cadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
