"""<Migration message>

Revision ID: 2c74fa860624
Revises: 563d5d82a055
Create Date: 2021-04-16 16:23:46.081924

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2c74fa860624'
down_revision = '563d5d82a055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licences', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('licences', sa.Column('url', sa.String(), nullable=True))
    op.drop_index('ix_licences_name', table_name='licences')
    op.create_index(op.f('ix_licences_fullname'), 'licences', ['fullname'], unique=False)
    op.drop_column('licences', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licences', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_licences_fullname'), table_name='licences')
    op.create_index('ix_licences_name', 'licences', ['name'], unique=False)
    op.drop_column('licences', 'url')
    op.drop_column('licences', 'fullname')
    # ### end Alembic commands ###
