"""adding columns to user table : modif_date...

Revision ID: 3fbb0a8f4814
Revises: b8d442a77507
Create Date: 2021-04-19 15:25:42.779910

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3fbb0a8f4814'
down_revision = 'b8d442a77507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
