"""adding columns to user table : workspaces and datasets.. + others

Revision ID: 41a4aa2d5be8
Revises: 23131606ded8
Create Date: 2021-04-16 19:31:52.916926

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '41a4aa2d5be8'
down_revision = '23131606ded8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
