"""changing licences models

Revision ID: 47deac221ff8
Revises: 2c74fa860624
Create Date: 2021-04-16 16:26:59.895765

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '47deac221ff8'
down_revision = '2c74fa860624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licences', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('licences', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licences', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('licences', 'category')
    # ### end Alembic commands ###
