"""adding columns to user table : workspaces and datasets

Revision ID: 49695a67bd8d
Revises: 4690724354ba
Create Date: 2021-04-16 18:27:04.981202

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '49695a67bd8d'
down_revision = '4690724354ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
