"""add comments table

Revision ID: 4dbc522dc2cd
Revises: fb5013f037a9
Create Date: 2021-03-26 10:32:49.810701

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4dbc522dc2cd'
down_revision = 'fb5013f037a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_index('ix_comments_body', table_name='comments')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_index('ix_comments_body', 'comments', ['body'], unique=False)
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
