"""add tablemeta table

Revision ID: 785f433e29da
Revises: d18c89cc6c85
Create Date: 2021-05-06 16:05:32.723851

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '785f433e29da'
down_revision = 'd18c89cc6c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablemetas', sa.Column('table_data_uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_tablemetas_table_data_uuid'), 'tablemetas', ['table_data_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tablemetas_table_data_uuid'), table_name='tablemetas')
    op.drop_column('tablemetas', 'table_data_uuid')
    # ### end Alembic commands ###
