"""trtying many to one between workspaces and datasets

Revision ID: 85d1c7fc2313
Revises: 2088c1841256
Create Date: 2021-04-20 11:00:43.657956

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '85d1c7fc2313'
down_revision = '2088c1841256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('datasets', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'datasets')
    # ### end Alembic commands ###
