"""add tablemeta table

Revision ID: ae7472e1e9cb
Revises: fae6593e6849
Create Date: 2021-05-06 11:35:37.901469

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ae7472e1e9cb'
down_revision = 'fae6593e6849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablemetas', sa.Column('licence', sa.String(), nullable=True))
    op.add_column('tablemetas', sa.Column('table_fields', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_tablemetas_licence'), 'tablemetas', ['licence'], unique=False)
    op.drop_column('tablemetas', 'icon')
    op.drop_column('tablemetas', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablemetas', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tablemetas', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tablemetas_licence'), table_name='tablemetas')
    op.drop_column('tablemetas', 'table_fields')
    op.drop_column('tablemetas', 'licence')
    # ### end Alembic commands ###
