"""trtying many to one between workspaces and datasets

Revision ID: b3524c002189
Revises: 3fbb0a8f4814
Create Date: 2021-04-19 22:11:07.587278

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b3524c002189'
down_revision = '3fbb0a8f4814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
