"""adding columns to user table : modif_date

Revision ID: b8d442a77507
Revises: 41a4aa2d5be8
Create Date: 2021-04-19 11:31:21.216523

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b8d442a77507'
down_revision = '41a4aa2d5be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modif_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modif_date')
    # ### end Alembic commands ###
