"""adding columns to user table : workspaces and datasets

Revision ID: c9beacec9912
Revises: 49695a67bd8d
Create Date: 2021-04-16 18:28:16.951175

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c9beacec9912'
down_revision = '49695a67bd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
