"""add tablemeta table

Revision ID: d18c89cc6c85
Revises: 273a44740963
Create Date: 2021-05-06 15:08:53.638969

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd18c89cc6c85'
down_revision = '273a44740963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
