"""trtying many to one between workspaces and datasets

Revision ID: e8f4ab726451
Revises: 85d1c7fc2313
Create Date: 2021-04-20 20:02:26.272416

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e8f4ab726451'
down_revision = '85d1c7fc2313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
