"""migration postgresql diff env config

Revision ID: f44b614e4ebd
Revises: 42e07fa5decc
Create Date: 2021-03-29 13:31:13.979415

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f44b614e4ebd'
down_revision = '42e07fa5decc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
