"""add tablemeta table

Revision ID: fae6593e6849
Revises: e8f4ab726451
Create Date: 2021-05-06 08:46:49.496731

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae6593e6849'
down_revision = 'e8f4ab726451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tables_description', table_name='tables')
    op.drop_index('ix_tables_id', table_name='tables')
    op.drop_index('ix_tables_title', table_name='tables')
    op.drop_table('tables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('read', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('write', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='tables_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='tables_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tables_pkey')
    )
    op.create_index('ix_tables_title', 'tables', ['title'], unique=False)
    op.create_index('ix_tables_id', 'tables', ['id'], unique=False)
    op.create_index('ix_tables_description', 'tables', ['description'], unique=False)
    # ### end Alembic commands ###
